<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // Curug Telu (Category ID: 1)
            [
                'category_id' => 1,
                'name' => 'Tiket Masuk Dewasa',
                'description' => 'Tiket masuk lokasi wisata Curug Telu untuk pengunjung dewasa',
                'price' => 10000,
                'stock' => 100,
                'criteria' => 'perorangan',
                'status' => 'published',
                'favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Paket Foto Curug Telu',
                'description' => 'Paket khusus untuk pengunjung yang ingin mendokumentasikan momen di Curug Telu',
                'price' => 25000,
                'stock' => 50,
                'criteria' => 'perorangan',
                'status' => 'published',
                'favorite' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Curug Ceheng (Category ID: 2)
            [
                'category_id' => 2,
                'name' => 'Tiket Masuk',
                'description' => 'Tiket masuk area Curug Ceheng untuk pengunjung',
                'price' => 6000,
                'stock' => 200,
                'criteria' => 'perorangan',
                'status' => 'published',
                'favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Curug Jenggala (Category ID: 3)
            [
                'category_id' => 3,
                'name' => 'Tiket Masuk',
                'description' => 'Tiket masuk area Curug Jenggala untuk pengunjung',
                'price' => 8000,
                'stock' => 150,
                'criteria' => 'perorangan',
                'status' => 'published',
                'favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Paket Foto Hati',
                'description' => 'Paket foto di dek kayu berbentuk hati Curug Jenggala',
                'price' => 20000,
                'stock' => 50,
                'criteria' => 'perorangan',
                'status' => 'published',
                'favorite' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Museum Jenderal Sudirman (Category ID: 19)
            [
                'category_id' => 19,
                'name' => 'Tiket Masuk Dewasa',
                'description' => 'Tiket masuk Museum Jenderal Sudirman untuk pengunjung dewasa',
                'price' => 3000,
                'stock' => 300,
                'criteria' => 'perorangan',
                'status' => 'published',
                'favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 19,
                'name' => 'Paket Edukasi',
                'description' => 'Paket kunjungan dengan pemandu untuk rombongan pelajar',
                'price' => 15000,
                'stock' => 100,
                'criteria' => 'rombongan',
                'status' => 'published',
                'favorite' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Lokawisata Baturaden (Category ID: 16)
            [
                'category_id' => 16,
                'name' => 'Tiket Masuk Dewasa (Senin-Jumat)',
                'description' => 'Tiket masuk Lokawisata Baturaden untuk pengunjung dewasa pada hari kerja',
                'price' => 20000,
                'stock' => 200,
                'criteria' => 'perorangan',
                'status' => 'published',
                'favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 16,
                'name' => 'Tiket Masuk Dewasa (Sabtu-Minggu)',
                'description' => 'Tiket masuk Lokawisata Baturaden untuk pengunjung dewasa pada akhir pekan',
                'price' => 25000,
                'stock' => 200,
                'criteria' => 'perorangan',
                'status' => 'published',
                'favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 16,
                'name' => 'Tiket Masuk Anak (Senin-Jumat)',
                'description' => 'Tiket masuk Lokawisata Baturaden untuk anak-anak pada hari kerja',
                'price' => 10000,
                'stock' => 200,
                'criteria' => 'perorangan',
                'status' => 'published',
                'favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 16,
                'name' => 'Tiket Masuk Anak (Sabtu-Minggu)',
                'description' => 'Tiket masuk Lokawisata Baturaden untuk anak-anak pada akhir pekan',
                'price' => 12500,
                'stock' => 200,
                'criteria' => 'perorangan',
                'status' => 'published',
                'favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Taman Botani Baturaden (Category ID: 11)
            [
                'category_id' => 11,
                'name' => 'Tiket Masuk Dewasa (Senin-Jumat)',
                'description' => 'Tiket masuk Taman Botani Baturaden untuk pengunjung dewasa pada hari kerja',
                'price' => 15000,
                'stock' => 200,
                'criteria' => 'perorangan',
                'status' => 'published',
                'favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 11,
                'name' => 'Tiket Masuk Dewasa (Sabtu-Minggu)',
                'description' => 'Tiket masuk Taman Botani Baturaden untuk pengunjung dewasa pada akhir pekan',
                'price' => 20000,
                'stock' => 200,
                'criteria' => 'perorangan',
                'status' => 'published',
                'favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 11,
                'name' => 'Tiket Masuk Lansia/Disabilitas',
                'description' => 'Tiket masuk dengan diskon 50% untuk lansia dan penyandang disabilitas',
                'price' => 7500,
                'stock' => 100,
                'criteria' => 'perorangan',
                'status' => 'published',
                'favorite' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Pancuran Pitu (Category ID: 10)
            [
                'category_id' => 10,
                'name' => 'Tiket Masuk Wana Wisata',
                'description' => 'Tiket masuk area Wana Wisata untuk mengakses Pancuran Pitu',
                'price' => 25000,
                'stock' => 100,
                'criteria' => 'perorangan',
                'status' => 'published',
                'favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 10,
                'name' => 'Paket Berendam di Pancuran',
                'description' => 'Tambahan untuk berendam di area pancuran mata air panas',
                'price' => 5000,
                'stock' => 50,
                'criteria' => 'perorangan',
                'status' => 'published',
                'favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // The Village Purwokerto (Category ID: 17)
            [
                'category_id' => 17,
                'name' => 'Tiket Masuk (Senin-Jumat)',
                'description' => 'Tiket masuk The Village Purwokerto pada hari kerja',
                'price' => 25000,
                'stock' => 200,
                'criteria' => 'perorangan',
                'status' => 'published',
                'favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 17,
                'name' => 'Tiket Masuk (Sabtu-Minggu)',
                'description' => 'Tiket masuk The Village Purwokerto pada akhir pekan',
                'price' => 30000,
                'stock' => 200,
                'criteria' => 'perorangan',
                'status' => 'published',
                'favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Baturraden Adventure Forest (Category ID: 18)
            [
                'category_id' => 18,
                'name' => 'Paket Gathering 1 Hari',
                'description' => 'Paket aktivitas petualangan untuk rombongan minimal 50 orang, durasi 1 hari',
                'price' => 395000,
                'stock' => 50,
                'criteria' => 'rombongan',
                'status' => 'published',
                'favorite' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 18,
                'name' => 'Paket Gathering 2 Hari 1 Malam',
                'description' => 'Paket aktivitas petualangan untuk rombongan minimal 50 orang, durasi 2 hari 1 malam',
                'price' => 725000,
                'stock' => 30,
                'criteria' => 'rombongan',
                'status' => 'published',
                'favorite' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 18,
                'name' => 'Paket Outbond Pelajar SD/SMP',
                'description' => 'Paket outbond untuk rombongan pelajar SD dan SMP, minimal 50 orang',
                'price' => 255000,
                'stock' => 50,
                'criteria' => 'rombongan',
                'status' => 'published',
                'favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 18,
                'name' => 'Paket Outbond Pelajar SMA/Mahasiswa',
                'description' => 'Paket outbond untuk rombongan pelajar SMA dan mahasiswa, minimal 50 orang',
                'price' => 305000,
                'stock' => 50,
                'criteria' => 'rombongan',
                'status' => 'published',
                'favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 18,
                'name' => 'Paket Camping Keluarga',
                'description' => 'Paket camping untuk 2 orang dewasa dan 2 anak',
                'price' => 2500000,
                'stock' => 20,
                'criteria' => 'rombongan',
                'status' => 'published',
                'favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 18,
                'name' => 'Paket Paintball',
                'description' => 'Aktivitas paintball per orang',
                'price' => 250000,
                'stock' => 30,
                'criteria' => 'perorangan',
                'status' => 'published',
                'favorite' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 18,
                'name' => 'Canyoning Trek Lawang',
                'description' => 'Paket canyoning trek Lawang, minimal 20 orang',
                'price' => 475000,
                'stock' => 20,
                'criteria' => 'rombongan',
                'status' => 'published',
                'favorite' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 18,
                'name' => 'Canyoning Trek Bening',
                'description' => 'Paket canyoning trek Bening, minimal 20 orang',
                'price' => 575000,
                'stock' => 20,
                'criteria' => 'rombongan',
                'status' => 'published',
                'favorite' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 18,
                'name' => 'Canyoning Trek Kinyami',
                'description' => 'Paket canyoning trek Kinyami, minimal 20 orang',
                'price' => 575000,
                'stock' => 20,
                'criteria' => 'rombongan',
                'status' => 'published',
                'favorite' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 18,
                'name' => 'Body Rafting',
                'description' => 'Aktivitas body rafting, minimal 5 orang',
                'price' => 250000,
                'stock' => 30,
                'criteria' => 'perorangan',
                'status' => 'published',
                'favorite' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ];

        DB::table('products')->insert($products);
    }
}
